[package]
name = "rocket-templates"
version = "0.1.0"
authors = ["HideakiImamura <gohome.x105.gn@gmail.com>"]

[dependencies]
rocket = "0.3.5"
rocket_codegen = "0.3.5"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["tera_templates"]
