[package]
name = "reqwest-example"
version = "0.1.0"
authors = ["HideakiImamura <gohome.x105.gn@gmail.com>"]

[dependencies]
reqwest = "0.8.1"
serde_json = "1.0.6"
serde = "1.0.21"
serde_derive = "1.0.21"